Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202404.26.0"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    config.vm.network "private_network", ip: ENV['ip_address']
    config.vm.hostname = ENV['vm_hostname']

    #prepare ssh and instal ansible
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        sudo sed -i '/PasswordAuthentication no/c\PasswordAuthentication yes' /etc/ssh/sshd_config
        sudo systemctl restart ssh
        sudo apt update -y
        sudo apt install ansible -y
        sudo apt install sshpass -y
        ln -s /vagrant/playbook/ /home/vagrant/
        ln -s /vagrant/server.txt /home/vagrant/
        ln -s /vagrant/ssh_config.sh /home/vagrant/
    SHELL
end