Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end
    config.vm.network "private_network", ip: ENV['ip_address']
    config.vm.hostname = ENV['vm_hostname']
end