Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    config.vm.network "private_network", ip: ENV['ip_address']
    config.vm.hostname = ENV['vm_hostname']

    #prepare ssh and instal ansible
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        sudo sed -i '/PasswordAuthentication no/c\PasswordAuthentication yes' /etc/ssh/sshd_config
        sudo systemctl restart sshd
        sudo ln -s /vagrant/playbook ~/
        sudo apt update -y
        sudo apt install ansible -y
        sudo apt install sshpass -y
    SHELL
end