# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  # if Vagrant.has_plugin?("vagrant-vbguest") then
  #   config.vbguest.auto_update = false
  # end
end