Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: ENV['ip_address']
    config.vm.hostname = ENV['vm_hostname']
    config.vm.define ENV['vm_hostname']
end