Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202404.26.0"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end
    config.vm.network "private_network", ip: ENV['ip_address']
    config.vm.hostname = ENV['vm_hostname']

    #prepare ssh
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        sudo sed -i '/PasswordAuthentication no/c\PasswordAuthentication yes' /etc/ssh/sshd_config
        sudo systemctl restart ssh
    SHELL
end